export const dropdownDatas = {
    'dropdownLabels': [
        'Sincan',
        'Lale',
        'Elvankent',
        'Eryaman',
        'Ozgunes',
        'Etimesgut',
        'Hava Duraği',
        'Yildirim',
        'Behicbey',
        'Motor Duragi',
        'Gazi',
        'Gazi Mahallesi',
        'Hipodrom',
        'Ankara',
        'Yenisehir',
        'Kurtuluş',
        'Cebeci',
        'Demirlibahçe',
        'Saimekadin',
        'Mamak',
        'Bagderesi',
        'Uregil',
        'Kostence',
        'Kayas'
    ],
    'dropdownValues': [
        '-sincan',
        '-lale',
        '-elvankent',
        '-eryaman',
        '-ozgunes',
        '-etimesgut',
        '-havaduragi',
        '-yildirim',
        '-behicbey',
        '-motor-duragi',
        '-gazi',
        '-gazi-mahallesi',
        '-hipodrom',
        '-ankara',
        '-yenisehir',
        '-kurtulus',
        '-cebeci',
        '-demirlibahce',
        '-saimekadin',
        '-mamak',
        '-bagderesi',
        '-uregil',
        '-kostence',
        '-kayas',
    ]
}

export const radioValues = [
    { label: 'Kayaş to Sincan', value: 'kayas-to-sincan' },
    { label: 'Sincan to Kayaş', value: 'sincan-to-kayas' }
];